### PR TITLE
Link to Ankita story about joining The Good Docs

### PR DESCRIPTION
**Pull request by camerons**
> __ALL Pull-Requests require an associated [Issue](https://github.com/thegooddocsproject/templates/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) as documented in [How to contribute](https://github.com/thegooddocsproject/templates/blob/master/CONTRIBUTING.md#contributing).__

## Purpose / why

>  Link to Ankita story about joining The Good Docs from our press page: https://github.com/thegooddocsproject/thegooddocsproject.github.io/issues/59

## What changes were made?

> Linked to Ankita's article.

## Verification

> Verify text is okay, and link works.

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Are issues linked correctly?
* [ ] Is this PR labeled correctly?
* [ ] If template updates: do they align with [developers.google.com/style/](https://developers.google.com/style/)?
* [ ] Did the PR receive at least one :+1: and no :-1: from core-maintainers?
* [ ] On merging, did you complete the merge using [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue)?
* [ ] On merging, did you add any applicable notes to a [draft release](https://github.com/thegooddocsproject/templates/releases) and link to this PR?

### CODE REVIEW

**Comment by viraji** [comment]
This is good to go!

**Comment by camerons** [comment]
Thanks @viraji , can you please tick the approve button in your review.

**Review by viraji — APPROVED** [review]
Good to go.

**Comment by techtrailhead** [comment]
Good to go!

**Review by techtrailhead — APPROVED** [review]
Good to go!

**Pull request merged**
